### ISSUE TITLE
Trailing comma causes server error on /blog/

### ISSUE THREAD

**Issue by mikl** [montylounge/django-mingus#10]
Sorry to keep bombarding your issue queue, but basic-apps doesn't have an issue queue, so here goes:

On line 16 of basic.blog.views:

```
    page_size = getattr(settings,'BLOG_PAGESIZE', paginate_by),
```

The trailing comma here causes Python to return a one-item tuple (yes, that confused me at first), which then causes a TypeError in django/core/paginator.py in _get_num_pages (line 64).

So a quick fix would be to remove the comma, then everything seems to work as expected :)

**Comment by montylounge** [comment]
np! I love it.

That's actually legacy: page_size = getattr(settings,'BLOG_PAGESIZE', paginate_by),

I need to remove it! That setting should come from the basic.blog.models.Setting model

So I'll resolve it one of these evenings.

**Comment by montylounge** [comment]
Pushed resolution now. It's in the 0.8.1 tag
