### ISSUE TITLE
Google web tools

### ISSUE THREAD

**Issue by dartdog** [montylounge/django-mingus#11]
In an effort to get the Google web tools going, I placed the entire meta string <> to </> in the analytics section of admin.. it did not work... I looked to see if anything from that box on admin made it into the HTML before the <body> and could not see anything so I simply place the string in base.html.... Is there something I'm missing? is there something else I should put in the admin box for G Analytics?

**Comment by montylounge** [comment]
The textbox in the Google Analytics app only exists to put your google analytics code in there. Usually looks something like this: UA-9891234-1

The app then renders the appropriate JS at the bottom of your html.

If you need to have google verify your site, then just place the meta string in the <head> of base.html template

Hope that helps!

**Comment by dartdog** [comment]
great
