### ISSUE TITLE
Most formating stripped from RSS output

### ISSUE THREAD

**Issue by dartdog** [montylounge/django-mingus#12]
All <p> and </p> are gone at least one link survived,,

**Comment by dartdog** [comment]
I attempted to put begin paragraph and end paragraph html in the post here, it got used, unlike the rss!

**Comment by montylounge** [comment]
You can edit the rendering of the RSS in /templates/feeds/ directory to meet your needs.

**Comment by dartdog** [comment]
can you give me a bit more of a clue how to just allow full html/markdown as the orig post? so that a fully formatted feed is produced,, I see {{ obj.body_markup|safe }} in posts_description.html which seems to be the filter for the body...

**Comment by montylounge** [comment]
Will fix in a near future release.
