### ISSUE TITLE
Search template missing important information

### ISSUE THREAD

**Issue by scelis** [montylounge/django-mingus#14]
It looks as though there are two templates for displaying search results:

templates/blog/post_search.html
templates/proxy/proxy_search.html

Currently, templates/proxy/proxy_search.html is being used. However, this template is missing the following pieces of information:

1) The extended title.
2) The "Search results for:" block.
3) The "message" paragraph (not sure what this is used for).

These all exist in the other template.

I'd create a patch for you but I'm not sure which template you want fixed up. :)

**Comment by montylounge** [comment]
Scellis, thanks for filing the issue.

proxy_search.html is new and allows the user to search all the content that Mingus creates whereas the post_search.html template is used for the view (no longer wired up) that allows the user to search just posts.

I'll take a look at what you say is missing soon, but feel free to submit a patch as well :)

**Comment by scelis** [comment]
This should be fixed in my branch:

http://github.com/scelis/django-mingus/commits/issue14

I have also submitted a pull request.

**Comment by montylounge** [comment]
Terrific, I'll pull asap.

**Comment by montylounge** [comment]
resolved in dev branch. will be pushed with 0.9

**Comment by montylounge** [comment]
resolved in 0.9alpha and moving forward.
