### ISSUE TITLE
Markdown not properly evaluated in RSS feed

### ISSUE THREAD

**Issue by scelis** [montylounge/django-mingus#15]
When viewing the RSS feed at http://blog.server.com/feeds/latest/ , all posts written in Markdown are not properly evaluated. My RSS reader simply displays all of the Markdown text on a single line.

**Comment by scelis** [comment]
This should be fixed in my branch:

http://github.com/scelis/django-mingus/tree/issue15

I have also submitted a pull request.

**Comment by montylounge** [comment]
Terrific. I'll pull asap.

**Comment by montylounge** [comment]
resolved in dev branch. will be pushed with 0.9

**Comment by montylounge** [comment]
resolved in 0.9alpha and moving forward.
