### ISSUE TITLE
"About" block escapes all HTML

### ISSUE THREAD

**Issue by scelis** [montylounge/django-mingus#16]
When editing the 'About' setting, the UI provides the following hint:

```
Accepts RAW html. By default, appears in right rail.
```

However, when RAW html is entered, this HTML is escaped on display and you can actually see all of the tags in the text of the block.

The BLOG_SETTINGS.about variable needs to be marked as safe in the base.html template. I will submit a patch to this momentarily.

**Comment by scelis** [comment]
Fixed in: http://github.com/scelis/django-mingus/tree/issue16

Pull request sent.

**Comment by montylounge** [comment]
nice find, will add.

**Comment by montylounge** [comment]
resolved in dev branch. will be pushed with 0.9

**Comment by montylounge** [comment]
resolved in 0.9alpha and moving forward.
