### ISSUE TITLE
Fix for server error on nonexisting slug.

### ISSUE THREAD

**Issue by mikl** [montylounge/django-mingus#17]
I fixed a small issue with invalid blog URLs causing an internal server error. It's just a one-line change:

http://github.com/mikl/django-basic-apps/commit/e22a7393d06e00263e7d8c20096a7a909e6e8c24

**Comment by montylounge** [comment]
Thx, will add.

**Comment by montylounge** [comment]
resolved in dev branch. will be pushed with 0.9

**Comment by montylounge** [comment]
resolved in 0.9alpha and moving forward.
