### ISSUE TITLE
Make mingus itself a reusable app

### ISSUE THREAD

**Issue by ghost** [montylounge/django-mingus#18]
Mingus seems like a great project.  However, it is packaged as a monolithic project, and is not terribly easy to integrate into other projects.  Possible to make mingus itself be reusable?

**Comment by montylounge** [comment]
Thanks for the kind words. I think you made my head explode - make an application that uses only reusable application a reusable application itself!

I like the idea but as it stands today Mingus is an example project on leveraging reusable apps. It will probably stay that way unless someone wants to fork it and give it a shot.
