### ISSUE TITLE
syncdb throwing an exception

### ISSUE THREAD

**Issue by mwarkentin** [montylounge/django-mingus#19]
I just tried setting up django-mingus both locally, and on a WebFaction instance.. when I do a syncdb, I get the following:

<pr>
(blog)[mwarkentin2@web56 mingus]$ ./manage.py syncdb
Syncing...
Installing json fixture 'initial_data' from '/home/mwarkentin2/.virtualenvs/blog/src/django-oembed/oembed/fixtures'.
Installing json fixture 'initial_data' from '/home/mwarkentin2/.virtualenvs/blog/src/django-quoteme/quoteme/fixtures'.
Installing json fixture 'initial_data' from '/home/mwarkentin2/webapps/blog/django-mingus/mingus/../mingus/fixtures'.
Problem installing fixture '/home/mwarkentin2/webapps/blog/django-mingus/mingus/../mingus/fixtures/initial_data.json': Traceback (most recent call last):
  File "/home/mwarkentin2/webapps/blog/lib/python2.5/django/core/management/commands/loaddata.py", line 153, in handle
    obj.save()
  File "/home/mwarkentin2/webapps/blog/lib/python2.5/django/core/serializers/base.py", line 163, in save
    models.Model.save_base(self.object, raw=True)
  File "/home/mwarkentin2/webapps/blog/lib/python2.5/django/db/models/base.py", line 506, in save_base
    created=(not record_exists), raw=raw)
  File "/home/mwarkentin2/webapps/blog/lib/python2.5/django/dispatch/dispatcher.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwarkentin2/.virtualenvs/blog/src/django-proxy-tip/django_proxy/signals.py", line 55, in proxy_save
    active_field = getattr(cls, 'active')
AttributeError: class ProxyMeta has no attribute 'active'
</pre>

**Comment by montylounge** [comment]
Are you running on master? A specific version (tag)?

**Comment by mwarkentin** [comment]
I was following the instructions in install.textile, so I used git clone git://github.com/montylounge/django-mingus.git

**Comment by montylounge** [comment]
what DB are you using? Postgres, MySQL?

**Comment by mwarkentin** [comment]
I'm using Postgres 8.3.1

**Comment by montylounge** [comment]
Thanks. I'll take a peak into your install txt file you sent over.

**Comment by newmaniese** [comment]
This is related to http://bitbucket.org/montylounge/django-proxy/issue/1/active-is-not-optional-if-object-is-not . Applying the attached patch fixes it for me.

**Comment by pmarti** [comment]
I second last comment, applying the patch fixes it for me too

**Comment by montylounge** [comment]
great. i'll add soon, sorry for delay just some personal stuff keeping me away from the project recently.

**Comment by gour** [comment]
Let me just add that the above patch fixes the issue for me too.

**Comment by montylounge** [comment]
thanks all. the patch and updates are forthcoming. hope to get a .9 our soon with issues and updates.

**Comment by montylounge** [comment]
I've created a new repo on github that hosts the bug fix and future improvements to this project. Release 0.9 of Mingus will reference this repo change. Thanks for your help and patience. Here's the URL: http://github.com/montylounge/django-proxy

**Comment by montylounge** [comment]
resolved in dev branch. will be pushed with 0.9

**Comment by montylounge** [comment]
resolved in 0.9alpha and moving forward.
