### ISSUE TITLE
Configuration files should be read as UTF-8

### ISSUE THREAD

**Issue by mikl** [montylounge/django-mingus#2]
Since manager names (that can easily contain non-ASCII characters) are input into the config file, it would be helpful to have the UTF-8 coding line that Python requires to parse those files.

```
# -*- coding: utf-8 -*-
```

**Comment by mikl** [comment]
Fix available here: http://github.com/mikl/django-mingus/commit/162b8b515ba98a71cecc0eb2271e105d33540271 :)

**Comment by montylounge** [comment]
Pushed to master. Thx.
