### ISSUE TITLE
Wrap text around picture (use class="small_left) tag on photo

### ISSUE THREAD

**Issue by dartdog** [montylounge/django-mingus#20]
Well this is an enhancement and I'll do it if i can find it! as of now no matter how you insert a picture the class is &lt div class = "post-img clearfix"> so the css style covers the width of the blog space and text cannot wrap.. I'd like to apply a different class (class="small_left" depending on the tag when the picture is inserted and the apply style with a narrow width, floated left so the text can wrap.. The current post at oswco.com shows the issue.

I may yet find the stuff, but pointers appreciated

**Comment by montylounge** [comment]
Great, please post the fix and I'll try and include it.
