### ISSUE TITLE
Very strange when requesting a non exsting date from archive get debug page even w debug off

### ISSUE THREAD

**Issue by dartdog** [montylounge/django-mingus#21]
Another item I've been trying to track down is some errors from the error log
when something hits my site requesting items from too far back I get a Django Debug error page rather than the nice page does not exist that you have in the normal flow, I have all debug set to false.. and this is the only condition that gives me the problem example: http://oswco.org/2009/jul/31/

other errors/ not founds work fine.. Again I'm looking and if I find I'll report back but pointers appreciated.

**Comment by montylounge** [comment]
I'll take a look and try and post a fix shortly. thanks!

**Comment by montylounge** [comment]
Any update?

**Comment by montylounge** [comment]
Closing. Can't reproduce.
