### ISSUE TITLE
docs/INSTALL.textile pip doc is out of date

### ISSUE THREAD

**Issue by brixtonasias** [montylounge/django-mingus#22]
The doc refers to version 0.4 of pip (due to a bug in 0.5 that got fixed by the pip-guys). After talking to jezdez (http://github.com/jezdez) pip is now included in virtualenv and it is not needed to install it manually.

Worked fine for me w/o installing pip to the virtualenv. Please double check though ;-)

**Comment by montylounge** [comment]
No, you're correct. I can update the docs - just been busy (had a baby 3 days ago and moved into an older house about a month ago). Sorry for delays, life just been keeping me busy.
