### ISSUE TITLE
xmlrpc interface for remote publishing

### ISSUE THREAD

**Issue by gour** [montylounge/django-mingus#23]
Hi!

I'm looking for a django-based blog for which I'd be able to remotely post (in reST) from Emacs.

Byteflow (http://byteflow.su/) can do it, so I wonder what do you think about it for Mingus?

Sincerely,
Gour

**Comment by montylounge** [comment]
Gour, I don't need the feature myself but if you fork and add the feature I will merge into Mingus core. Thanks!@

**Comment by montylounge** [comment]
Closing. Not adding unless someone wants to contribute.
