### ISSUE TITLE
multi-blog support

### ISSUE THREAD

**Issue by gour** [montylounge/django-mingus#25]
Hiya!

Will McGugan writes in http://www.willmcgugan.com/blog/tech/2009/3/14/the-low-down-on-django-techblog/ post: "I want to blog on a variety of subjects, but because some of the things I post about (namely the geeky stuff) are only of interest to a select few, I risk turning away visitors who aren't interested in those techy posts. Categories and tags are one solution to this, but I prefer to have a number of blogs under an umbrella blog, each with its own posts, templates and tags. In Techblog, there is also a concept of a channel which appears exactly like a blog from the front-end, but aggregates posts & tags from one or more blogs. In this site, the home-page at / is actually a channel consisting of /blog/tech/ and /blog/personal."

I'm curious if something like that can be done in Mingus?

Sincerely,
Gour

**Comment by montylounge** [comment]
Mingus supports one blog engine, not multiple.
