### ISSUE TITLE
Sub pages menu-no show

### ISSUE THREAD

**Issue by dartdog** [montylounge/django-mingus#26]
Was trying to set up a sub page to a parent page /Test1/testsub/
Test1 shows up fine on parent page(main page) as well as all other pages, testsub never shows up. even when configured to the navbar neither on parent nor on sub page, where I'd like it, I'm looking into it to see if I can find it! Thought I'd go ahead and note here in case some one else sees or knows..

**Comment by montylounge** [comment]
Good note. Mingus default templates don't handle s subnav. Django-navbar was included as in introduction to the app itself. Any further template customization would be on a personal fork.

Thanks!

**Comment by dartdog** [comment]
FWIW Implemented nested nav with minor template change from Doug (dev of Django-navbar) and some css changes now located at http://github.com/dartdog/django-mingus/tree/getnestednav can now be seen live at http://dev.oswco.org

**Comment by montylounge** [comment]
awesome. I'll take a peek. Thanks.
