### ISSUE TITLE
enable feeds by categories

### ISSUE THREAD

**Issue by funollet** [montylounge/django-mingus#3]
This is already implemented in the 'blog' app, just needs to be enabled at `urls.py`. Patch included.

<pre>
diff --git a/mingus/urls.py b/mingus/urls.py
index 2a3c82d..124fc1f 100644
--- a/mingus/urls.py
+++ b/mingus/urls.py
@@ -15,6 +15,7 @@ admin.autodiscover()
 feeds = {
     'latest': BlogPostsFeed,
     'all': AllEntries,
+    'categories': BlogPostsByCategory,
 }
 #ex: /feeds/latest/
 #ex: /feeds/categories/django/
</pre>

**Comment by montylounge** [comment]
Yes it is. I'll add this so it's no longer hidden.

**Comment by montylounge** [comment]
just commited fix.
