### ISSUE TITLE
All my problems

### ISSUE THREAD

**Issue by hubbubca** [montylounge/django-mingus#32]
I'm sure this has everything to do with me and nothing to do with mingus but here's my current trouble.
## when I hit the "pip install -r stable-requirements.tx" step I'm getting a failure that ends with

_imaging.c: In function ‘DL_EXPORT’:

_imaging.c:3250: error: expected declaration specifiers before ‘init_imaging’

_imaging.c:3281: error: expected ‘{’ at end of input

error: command 'gcc' failed with exit status 1

---

Command /home/pshields/.virtualenvs/mingus/bin/python -c "import setuptools; **file**='/home/pshields/.virtualenvs/mingus/build/PIL/setup.py'; execfile('/home/pshields/.virtualenvs/mingus/build/PIL/setup.py')" install --single-version-externally-managed --record /tmp/pip-o6QuZ8-record/install-record.txt --install-headers /home/pshields/.virtualenvs/mingus/lib/include failed with error code 1
Storing complete log in ./pip-log.txt

**Comment by hubbubca** [comment]
Clearly I'm not grasping something... I just ran through it again and got the following:

Checking out python-twitter from hg+https://python-twitter.googlecode.com/hg/@7e5cb2db67352ac1fd7b40a3ec54fdef352f802f#egg=python_twitter-0.7_devel-py2.5-default checkout from hg+https://python-twitter.googlecode.com/hg/@7e5cb2db67352ac1fd7b40a3ec54fdef352f802f#egg=python_twitter-0.7_devel-py2.5-default (from -r stable-requirements.txt (line 37))
  Cloning hg https://python-twitter.googlecode.com/hg/ (to revision 7e5cb2db67352ac1fd7b40a3ec54fdef352f802f) to ./src/python-twitter
  Running setup.py egg_info for package python-twitter
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1721, in install_files
    if req_to_install.check_if_exists():
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1583, in check_if_exists
    dist = pkg_resources.get_distribution(self.req)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 270, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 156, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 423, in find
    raise VersionConflict(dist,req)     # XXX add more info
VersionConflict: (Pygments 1.0 (/usr/lib/pymodules/python2.6), Requirement.parse('Pygments==1.1.1'))

**Comment by montylounge** [comment]
Quick look seems like your virtualenv has a conflict with an already exiting PIL instance. I don't know you're setup but maybe try removing the other instance? I'm going to close this issue because it's an environment issue, but message me directly if you'd like me to help further.

**Comment by goldan** [comment]
I experience exactly the same issue (with PIL). Do you probably know any work-arounds? I can't install mingus because of this.

**Comment by goldan** [comment]
Just found the solution:
You need to install python-dev package.
sudo apt-get install python-dev
(from http://stackoverflow.com/questions/2967224/gcc-error-trying-to-install-pil-in-a-python2-6-virtualenv/2967565#2967565)

**Comment by montylounge** [comment]
Thanks for posting the resolution!
