### ISSUE TITLE
Problems when installing requirements

### ISSUE THREAD

**Issue by graz** [montylounge/django-mingus#33]
I found the following problem while installing the requirements with pip.:

...
Checking out django-view-cache-utils-tip from hg+https://bitbucket.org/kmike/django-view-cache-utils/@4408ad8f1751ee2fccb441d2a342c4ed710467a0#egg=django_view_cache_utils-tip checkout from hg+https://bitbucket.org/kmike/django-view-cache-utils/@4408ad8f1751ee2fccb441d2a342c4ed710467a0#egg=django_view_cache_utils-tip (from -r stable-requirements.txt (line 34))
  https://bitbucket.org/kmike/django-view-cache-utils/
  Clone in ./src/django-view-cache-utils-tip exists, and has correct URL (https://bitbucket.org/kmike/django-view-cache-utils/)
  Updating clone ./src/django-view-cache-utils-tip (to revision 4408ad8f1751ee2fccb441d2a342c4ed710467a0)
hg: unknown command 'fetch'
Mercurial Distributed SCM

**Comment by montylounge** [comment]
you need to install mercurial locally.

**Comment by graz** [comment]
graz@localhost:~/dev/django-mingus/mingus$ hg fetch
hg: unknown command 'fetch'
Mercurial Distributed SCM

basic commands:

 add        add the specified files on the next commit
 annotate   show changeset information by line for each file
 clone      make a copy of an existing repository
 commit     commit the specified files or all outstanding changes
 diff       diff repository (or selected files)
 export     dump the header and diffs for one or more changesets
 forget     forget the specified files on the next commit
 init       create a new repository in the given directory
 log        show revision history of entire repository or files
 merge      merge working directory with another revision
 parents    show the parents of the working directory or revision
 pull       pull changes from the specified source
 push       push changes to the specified destination
 remove     remove the specified files on the next commit
 serve      export the repository via HTTP
 status     show changed files in the working directory
 update     update working directory

use "hg help" for the full list of commands or "hg -v" for details
graz@localhost:~/dev/django-mingus/mingus$ hg --version
Mercurial Distributed SCM (version 1.3.1)

Copyright (C) 2005-2009 Matt Mackall mpm@selenic.com and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Hg is already installed

**Comment by graz** [comment]
After updating my pip version, things went well. Thanks for your support
