### ISSUE TITLE
Kinda weird: site settings not propigated to Blog settings

### ISSUE THREAD

**Issue by dartdog** [montylounge/django-mingus#34]
On my development blog I had changed my Site settings via to shorten the site name since it was messing up my layout,, could not figure out why my header was not updating when I looked at the database the site name in the blog_settings table was not changed although the site setting was,, the blog setting site name is not avail through the admin.. I am using Mysql if that might make a difference, granted most people don't change their site names often,, but it was a problem for me to figure out, I thought something weird was going on with cashing.

**Comment by montylounge** [comment]
Good catch!

The reason, currently, is that if you edit the django.contrib Site model it doesn't update the basic.blog Settings model. The blog_settings table has a denormalized reference to . The hack fix is to update the django.contrib Site instance and then go over to the basic.blog Settings instance and just save it again (the save method copies the Site model's name field to the Setting's model site_name field in the db.)

I have to add a signal to make this work correctly. Should be in the basic.blog fork Mingus uses within the next few days. Thanks for noting it.

**Comment by montylounge** [comment]
Resolved in latest commits on basic blog. Updated stable-requirements basic blog reference to pull from there.
