### ISSUE TITLE
Patch for INSTALL.textile

### ISSUE THREAD

**Issue by graz** [montylounge/django-mingus#35]
I find the following typo in INSTALL.textile document:

diff --git a/docs/INSTALL.textile b/docs/INSTALL.textile
index c5fce75..840c20b 100644
--- a/docs/INSTALL.textile
+++ b/docs/INSTALL.textile
@@ -14,7 +14,7 @@ It also assumes you have both subversion, mecurial, and git clients locally.
- ... wait a bit
- mv local_settings.py.template local_settings.py
- ./manage.py syncdb
  -\* .manage.py loaddata test_data.json
  +\* ./manage.py loaddata test_data.json
- ./manage.py runserver

**Comment by montylounge** [comment]
Thanks. I'll update.
