### ISSUE TITLE
runserver error

### ISSUE THREAD

**Issue by myhat123** [montylounge/django-mingus#38]
(myblog)hzg@debian:~/work/myblog/django-mingus/mingus$ ./manage.py runserver
Validating models...
0 errors found

Django version 1.1.1, using settings 'mingus.settings'
Development server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/hzg/.virtualenvs/myblog/lib/python2.5/site-packages/pygments/plugin.py:39: UserWarning: Module simplejson was already imported from /home/hzg/.virtualenvs/myblog/src/python-twitter/simplejson/**init**.pyc, but /home/hzg/.virtualenvs/myblog/lib/python2.5/site-packages is being added to sys.path
  import pkg_resources

When I visited http://localhost:8000/,
It can not continue to run the following step. Why?

but visiting http://localhost:8000/admin/, it works, and it is very nice.

**Comment by montylounge** [comment]
So when you try to visit the landing page it raise an exception? Does it display the landing page? UserWarning is non-fatal.

**Comment by myhat123** [comment]
no exception. I guess that it may visit a web site ( twitter, ie ) which is blocked by firewall. Whcih site will Mingus blog visit at home page?

**Comment by montylounge** [comment]
Ah, the mingus homepage does make an http request to delicious to grab popular Django posts on delicious. Check the base.html template for that code which would appear in the right rail. Let me know if that solves your issue. (if so I think I'll remove that from the template as I never considered firewall issues and I'd rather circumvent any possible obstacles.)

**Comment by montylounge** [comment]
Seems to be unique to user env.
