### ISSUE TITLE
Just noticed that django-db-log moved from Google code to Github

### ISSUE THREAD

**Issue by dartdog** [montylounge/django-mingus#39]
Just as a note for anyone trying to install, delete the line in the requirements file and install manually. from git hub. Just working on upgrading my install from.7 to the upgrade to .97

**Comment by montylounge** [comment]
Thanks. Will fix.

**Comment by acdha** [comment]
n.b. my 1.3 update branch also replaces django-db-log with django-sentry as I believe dcramer intends to completely supersed the project

**Comment by dartdog** [comment]
Thanks for the update, great to see you again, need to get my instance
updated,,I guess I'll wait a bit more 'till you have 1.3 checked out! (good
excuse!)

On Wed, Mar 23, 2011 at 4:42 PM, acdha <
reply@reply.github.com>wrote:

> n.b. my 1.3 update branch also replaces django-db-log with django-sentry as
> I believe dcramer intends to completely supersed the project
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/montylounge/django-mingus/issues/39#comment_909880

## 

Tom Brander
http://tombrander.com -Real Estate
http://oswco.com -Open Software
3763 West Jackson Blvd.
Birmingham, AL 35213
Phone 205-267-1089
@dartdog

**Comment by acdha** [comment]
It's pretty smooth now - if you want to see what it looks like, this branch was stable in limited testing using the example project:

https://github.com/acdha/django-mingus/tree/django-1.3-overhaul

**Comment by montylounge** [comment]
I'm making Mingus stable on 1.1.1 based on some user feedback (repos that moved, etc) now and will begin working with acdha on getting Mingus to support 1.3 next.
