### ISSUE TITLE
tag_detail view returning misleading results

### ISSUE THREAD

**Issue by skevy** [montylounge/django-mingus#4]
Perhaps this behavior is by design (although if it is I think its misguided), but instead of tag_detail returning proxy objects based on their direct association with the tag name in the URL, it searches the "tags" field, instead of doing a relationship based query.

For instance, you have two tags: django-minugs and mingus.  Going to http://[site]/tags/django-mingus results in the correct findset.  Going to http://[site]/tags/mingus returns both the objects tagged mingus and the objects tagged django-mingus.

**Comment by montylounge** [comment]
I'll look into this. I have a feeling that the objects you are referring to just happen to be tagged both "mingus" and "django-mingus" but I'll take a peek.

**Comment by skevy** [comment]
hey dude - thanks for the response - but the things weren't tagged with those two tags.  In tag_detail, line 181 of mingus/core/views.py:

queryset = Proxy.objects.published().filter(tags__icontains=tag.name).order_by('-pub_date'),

Notice how all it does is check if the tags field (a string) contains the name, which is equivalent to a SQL ILIKE statement.  So, if searching for mingus, it would return both mingus and django-mingus.

Hope this helps,
-Adam

**Comment by montylounge** [comment]
Ahh, I see.. I pulled this in from another repo. I will fix.

**Comment by skevy** [comment]
awesome - saves me the trouble :-)

**Comment by montylounge** [comment]
just commited fix.
