### ISSUE TITLE
Django slimmer middleware messes up code highlighting

### ISSUE THREAD

**Issue by boronine** [montylounge/django-mingus#40]
> So far Django-Slimmer hasn't introduced anything but great results.

ಠ_ಠ

`'slimmer.middleware.CompressHtmlMiddleware'` removes whitespaces from between tags, effectively removing all whitespaces in pygmentized code blocks.

**Comment by montylounge** [comment]
Feel free to remove from middleware since it's not a requirement for mingus to function properly. Not a bug, but thanks for the heads up.
