### ISSUE TITLE
"No distributions matching the version for BeautifulSoup==3.0.8" when installing

### ISSUE THREAD

**Issue by nicoechaniz** [montylounge/django-mingus#41]
When following the QuickStartGuide, this step:
pip install -r stable-requirements.txt

fails with error:
"No distributions matching the version for BeautifulSoup==3.0.8"

I just modified requirements.txt line to BeautifulSoup>=3.0.8 and it installed successfully.

**Comment by montylounge** [comment]
Thanks. Will fix.

**Comment by tomviner** [comment]
I believe this still needs doing :-)

**Comment by montylounge** [comment]
Yes it does. Ugh sorry. I'll get on it.
