### ISSUE TITLE
Basic blog - wrong name in twitter post check

### ISSUE THREAD

**Issue by pageworthy** [montylounge/django-mingus#48]
If the post to Twitter fails when making a blog post you get an error in basic/blog/signals.py the second to last line. The current line is "urllib2 import HttpError" but it should be "urllib2 import HTTPError".

**Comment by montylounge** [comment]
Thanks. Know issue. Will fix!

**Comment by montylounge** [comment]
Removed twitter and bitly integration in master. Won't support moving forward (for the time being at least).
