### ISSUE TITLE
Settings - default active_editor

### ISSUE THREAD

**Issue by montylounge** [montylounge/django-mingus#49]
I believe this is because a Settings blog instance has not been created but posting it anyway for me to follow up....

From a user:

Now i have error when i an a post

Exception Type: UnboundLocalError at /admin/blog/post/add/
Exception Value: local variable 'active_editor' referenced before assignment

Environment:

Request Method: GET
Request URL: http://domaine.com/admin/blog/post/add/
Django Version: 1.1.1
Python Version: 2.6.4
Installed Applications:
['django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 'django.contrib.admin', 'django.contrib.sitemaps', 'django.contrib.flatpages', 'django.contrib.redirects', 'django_extensions', 'tagging', 'djangodblog', 'disqus', 'basic.inlines', 'basic.blog', 'basic.bookmarks', 'basic.media', 'oembed', 'flatblocks', 'dbtemplates', 'navbar', 'sorl.thumbnail', 'template_utils', 'django_proxy', 'django_markup', 'google_analytics', 'robots', 'basic.elsewhere', 'compressor', 'contact_form', 'honeypot', 'sugar', 'quoteme', 'mingus.core', 'debug_toolbar', 'django_twitter', 'django_bitly', 'staticfiles', 'tinymce', 'django_wysiwyg', 'cropper', 'memcache_status', 'request'] Installed Middleware:
('django.middleware.common.CommonMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.middleware.doc.XViewMiddleware', 'django.contrib.redirects.middleware.RedirectFallbackMiddleware', 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware', 'slimmer.middleware.CompressHtmlMiddleware', 'sugar.middleware.debugging.UserBasedExceptionMiddleware', 'request.middleware.RequestMiddleware', 'djangodblog.DBLogMiddleware', 'debug_toolbar.middleware.DebugToolbarMiddleware')

Traceback:
File "/usr/local/lib/python2.6/site-packages/django/core/handlers/base.py" in get_response
92. response = callback(request, callback_args, *_callback_kwargs) File "/usr/local/lib/python2.6/site-packages/django/contrib/admin/options.py" in wrapper
226. return self.admin_site.admin_view(view)(args, kwargs) File "/usr/local/lib/python2.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
44. response = view_func(request, *args, kwargs) File "/usr/local/lib/python2.6/site-packages/django/contrib/admin/sites.py" in inner
186. return view(request, *args, *_kwargs) File "/opt/env/django-mingus/django-mingus/mingus/src/django-basic-apps/basic/blog/admin.py" in add_view
68. extra_context = { 'active_editor': active_editor }

Exception Type: UnboundLocalError at /admin/blog/post/add/
Exception Value: local variable 'active_editor' referenced before assignmen

**Comment by mysticbit** [comment]
# UPDATE FIX

Figured out what the problem was: ./manage.py loaddata core/fixtures/test_data.json
wasn't run properly. I didn't provide the appropriate path for the test_data.json file. 

---

Hi, 

I recently installed mingus and everything works great, except for this error you've posted. I can't perform any post without getting the error mentioned. Not sure if i'm doing something wrong. Look forward to a possible answer to this ticket. Thanks for Mingus!
