### ISSUE TITLE
FYI: remove all debug before deploy!

### ISSUE THREAD

**Issue by dartdog** [montylounge/django-mingus#50]
I'm still on .7 but had found that certain URL's would cough up debug even though debug was set to false.. made two changes to fix, removed ##'sugar.middleware.debugging.UserBasedExceptionMiddleware', from Middleware classes which says it should only be called for a super user but in my deploy on Webfaction seemed to be causing the debug instead of nice user page to display. And moved 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware', to last item in middleware,, now 500's get the nice user error page... as to why they are not regular 404's that is a topic for more investigation.. Also removed all reference to Django debug toolbar.

**Comment by pageworthy** [comment]
I had the same exact issues and did the same thing to fix them. For some reason Django debug toolbar was causing my local development to run super slow as well, once I commented it out everything was back to normal.

**Comment by montylounge** [comment]
Thanks. Moved Flatpage middleware after Debug middleware to enable toolbar on flatpages.
