### ISSUE TITLE
install of requeriments pending login

### ISSUE THREAD

**Issue by panchicore** [montylounge/django-mingus#56]
(blogenv)[panchicore@web92 mingus]$ pip-2.6 install -r stable-requirements.txt 
..
...
..... 
 Cloning hg https://sorl-thumbnail.googlecode.com/hg/ (to revision caf69b5206329d89282b4b8246a72e5aa77cb578) to /home/panchicore/webapps/panchicore_blog/blogenv/src/sorl-thumbnail-tip
http authorization required
realm: Google Code Mercurial Repository
user: 
password: 

(blogenv)[panchicore@web92 mingus]$ pip-2.6 install -r stable-requirements.txt 
Obtaining django-slimmer from git+git://github.com/hbussell/django-slimmer.git@61deecdbc7650664c2a23f36ed806c043c70d65e#egg=django_slimmer-0.0.1-py2.5-dev (from -r stable-requirements.txt (line 29))
  Updating /home/panchicore/webapps/panchicore_blog/blogenv/src/django-slimmer clone (to 61deecdbc7650664c2a23f36ed806c043c70d65e)
You are not currently on a branch, so I cannot use any
'branch.<branchname>.merge' in your configuration file.
Please specify which remote branch you want to use on the command
line and try again (e.g. 'git pull <repository> <refspec>').
See git-pull(1) for details.
  Complete output from command /home/panchicore/webapps/git/bin/git pull -q:

**Comment by alesasnouski** [comment]
I faced with this problem too. Just made a new virtualenv and started pip install -r requirements.txt again.

**Comment by ryan-blunden** [comment]
It seems PyDanny has switched off the Google Code project for Sorl and moved it to GitHub. Try replacing -e hg+https://sorl-thumbnail.googlecode.com/hg/#egg=sorl with -e git+git://github.com/sorl/sorl-thumbnail.git#egg=sorl

**Comment by panchicore** [comment]
thanks.

**Comment by montylounge** [comment]
Thanks guys. I'll update mingus source. Sorry for the confusion.
