### ISSUE TITLE
No textile parsing in the Tease section

### ISSUE THREAD

**Issue by brixtonasias** [montylounge/django-mingus#57]
When using textile elements in the Tease segment in the "Add post" section it won't get parsed / turned into html when saving.

A link for example "My link text":http://mylink.com/ will look like the textile declaration in the html view. So to post a link in the Tease section one has to use the classes html <a href...> tag.

**Comment by montylounge** [comment]
You can update the templates to support this by loading the django.contrib.markup templatetag and applying the textile filter.
