### ISSUE TITLE
Install Doc Correction

### ISSUE THREAD

**Issue by epicserve** [montylounge/django-mingus#58]
I needed to change the following line in https://github.com/montylounge/django-mingus/blob/master/docs/INSTALL.textile in order to load fixtures.

./manage.py loaddata test_data.json

to...

./manage.py loaddata core/fixtures/test_data.json

**Comment by montylounge** [comment]
I'm not sure why you needed to do this. If `core` is listed in your INSTALLED_APPS then by default Django will look in the fixture dirs of each app for the file specified. Closing.

**Comment by epicserve** [comment]
Not sure either... I would say if you can follow your install instructions with out needing my fix then it must be something specific to my setup or some other update made my fix unnecessary.
