### ISSUE TITLE
stable-requirements.txt module changes

### ISSUE THREAD

**Issue by epicserve** [montylounge/django-mingus#59]
I had to change a couple lines in stable-requirements.txt file in order for all the modules to install. The following are lines I used for the modules that wouldn't install.

```
-e git://github.com/jezdez/django-staticfiles.git#egg=django_staticfiles
-e git://github.com/sorl/sorl-thumbnail.git#egg=sorl_thumbnail
```

**Comment by montylounge** [comment]
Thanks. I just commited the fixes.
