### ISSUE TITLE
Invalid HTML fixes

### ISSUE THREAD

**Issue by mikl** [montylounge/django-mingus#6]
I've tweaked quite a bit with Mingus' default markup, making the demo content valid HTML (besides the oembed output).

There's a couple of commits you can cherry-pick if you want:

http://github.com/mikl/django-mingus/commit/a441a10f5dcb17ce4f40ed6164b6744ece358496
http://github.com/mikl/django-mingus/commit/0e7b3c26f0651531d9f8a43cb727a4633ab8bcd4

**Comment by montylounge** [comment]
Thanks, I'll take a look and pull in when possible.
