### ISSUE TITLE
Install instructions doesnt work

### ISSUE THREAD

**Issue by bjourne** [montylounge/django-mingus#61]
These instructions are incomplete: https://github.com/montylounge/django-mingus/blob/master/docs/INSTALL.textile There are many more packages you need to hunt for to get the Mingus example site to work which are not described.

**Comment by montylounge** [comment]
Bjourne, I'll give it another try but last I checked it was complete for getting a local instance running.

Are you running on master? What environment/OS? Any more details would be helpful as well.

Thanks and I'll run a few tests myself.
