### ISSUE TITLE
Beta version 4.0 of BeautifulSoup imports as bs4 instead of BeautifulSoup

### ISSUE THREAD

**Issue by ktonon** [montylounge/django-mingus#66]
`stable-requirements.txt` requires `BeautifulSoup>=3.0.8`.

I installed via `pip` and got version 4.0 of this library. Trying to do my first `syncdb` yields the error

```
ImportError: No module named BeautifulSoup
```

Looking at the `installed-files.txt` in the BeautifulSoup egg-info shows

```
../bs4/__init__.py
../bs4/dammit.py
...
```

Launching python and typing `import bs4` succeeds.

I changed the first line of `stable-requirements.txt` to `BeautifulSoup==3.2.0` and reinstalled. Everything worked all right.

**Comment by montylounge** [comment]
Resolved.
