### ISSUE TITLE
"Draft" blog posts are published on the front page plus confusing HTTP reply when opening a draft post's URL

### ISSUE THREAD

**Issue by mikl** [montylounge/django-mingus#8]
I'm not sure if this bug belongs here, but since the Proxy-object for a blog post is created immediately, regardless of the blog post's state, effectively defeating the purpose of the draft-state, since all Proxy-objects are displayed on the front page.

Clicking through to the post, however, generates a 301 (permanent redirect), so while the post is not displayed, this does not seem to be the correct behavior. Either a 404 or 403 would be fine, or if you want to keep the redirect, a 302 or 307 should be used, indicating that this URL may still be used in the future :)

**Comment by montylounge** [comment]
I don't believe you're correct about the proxy object being created immediately. If the post is set to draft the proxy object is not created. Proxy understands state, but I think there's an issue with flipping from draft to public and then back to draft. So I'll look into that and there is a bug with the preview in the admin. It's the last, or one of the last bugs I need to address.

Thanks for the feedback.

**Comment by mikl** [comment]
Yes, it seems that the Proxy is not created immediately, but if you edit and save a blog post created as a draft, a Proxy object is created, even if you do not change the state (ie. it is still "draft").

**Comment by montylounge** [comment]
Yes, this is the issue I was referring to. It's number one on my todo list when I have a chance. So it should be resolved shortly. Thanks.

**Comment by montylounge** [comment]
I've updated proxy and basic-blog (2 reusable app dependencies) to resolve this issue and issues related to preview. Tag 0.8 is the version I suggest pulling from. It contains these updates (just an update to the stable_requirements.txt really)
