### ISSUE TITLE
Tags have no slug, and are not suitable for URLs in some cases.

### ISSUE THREAD

**Issue by mikl** [montylounge/django-mingus#9]
The current tag view uses /tags/{{ tag.name }}/ as it's URL. That works fine if all your tags live up to `[-\w]+` as defined in urls.py, but does not work for tags like "Drupal 7", "#fail" or "hf&j" and a lot of other similar cases (not to mention Unicode characters), and since Django's backend does nothing to enforce these rules, you will end up with broken links or, in [this case](http://github.com/mikl/django-mingus/commit/981fec431cd09814f2efc3834eebd2df4f39a7ff), url reversion errors.

I don't see an immediate solution to this issue. Changing `django_tagging` to include a slug field would be the neat solution, but getting those changes merged upstream may be a bit hard.

**Comment by montylounge** [comment]
I like the idea but I'm going to punt on this for now. It should be included in django-tagging like you suggested. If you were to fork it and add this feature then I can pull it in. Thanks!
